// $(function(){
//   $(".box1").hover(function(){
//     $(".box-info").toggle();
// });
// $(".box2").hover(function(){
//   $(".box-info").toggle();
// });
// $(".box3").hover(function(){
//   $(".box-info").toggle();
// });
// $(".box4").hover(function(){
//   $(".box-info").toggle();
// });
// $(".box5").hover(function(){
//   $(".box-info").toggle();
// });
// $(".box6").hover(function(){
//   $(".box-info").toggle();
// });
// $(".box7").hover(function(){
//   $(".box-info").toggle();
// });
// $(".box8").hover(function(){
//   $(".box-info").toggle();
// });
// $(".box9").hover(function(){
//   $(".box-info").toggle();
// });
// $(".box10").hover(function(){
//   $(".box-info").toggle();
// });
//
// });
